<a href="https://colab.research.google.com/github/E1250/datascience_exercises_bootcamp/blob/numpy/011_020_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

### Table of contents:
* [Import biblioteki](#0)
* [Exercise 11](#1)
* [Exercise 12](#2)
* [Exercise 13](#3)
* [Exercise 14](#4)
* [Exercise 15](#5)
* [Exercise 16](#6)
* [Exercise 17](#7)
* [Exercise 18](#8)
* [Exercise 19](#9)
* [Exercise 20](#10)

### <a name='0'></a> Import of libraries

In [1]:
import numpy as np

np.__version__

'1.21.5'

### <a name='1'></a> Exercise 11
Build a one-dimensional numpy array of two-digit numbers.

__Expected result:__
```
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])
```

__Tip:__ Use the _np.arange()_ function.


In [7]:
# https://numpy.org/doc/stable/reference/generated/numpy.arange.html
np.arange(10,100,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

### <a name='2'></a> Exercise 12

Build the numpy array specified below:

```
array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
```

Note that the shape of the array is (9, 10).

__Tip:__ Use the _np.arange()_ function and the _np.ndarray.reshape()_ method.



In [10]:
# enter solution here
# https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html
array = np.arange(10,100,1)
array.reshape((9,10))

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### Reminder

### Identity matrix:

Identity matrix - a square matrix which coefficients are given by the formula:
$${\displaystyle a_{ij}={\begin{cases}1\quad {\text{dla}}\quad i=j\\[2pt]0\quad {\text{dla}}\quad i\neq j\end{cases}}}$$

#### Examples:
${\displaystyle I_{1}={\begin{bmatrix}1\end{bmatrix}},\;I_{2}={\begin{bmatrix}1&0\\0&1\end{bmatrix}},\;I_{3}={\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}}}$

### <a name='3'></a> Exercise 13

Build a _6x6_ two-dimensional array - identity matrix. Use the _int_ data type.

__Expected result:__

```
array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])
```
__Tip:__ Use the _np.eye()_ function.


In [11]:
# enter solution here
# https://numpy.org/devdocs/reference/generated/numpy.eye.html
np.eye(6,6,dtype = int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

### <a name='4'></a> Exercise 14

Set the random seed to 10. Then build a one-dimensional array consisting of 30 pseudo-randomly generated values from the uniform distribution above the $ [0, 1) $ interval.

__Expected result:__

```
array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578,
       0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317,
       0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895])
```
__Tip:__ Use the function _np.random.rand()_.


In [15]:
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html
np.random.rand(5,6)

array([[0.91714657, 0.12343352, 0.76988609, 0.65215969, 0.37986515,
        0.67766945],
       [0.32736327, 0.85650718, 0.0529782 , 0.37944176, 0.50237105,
        0.47925058],
       [0.60158484, 0.99047121, 0.81132444, 0.61761726, 0.59294321,
        0.85437677],
       [0.98534147, 0.55988384, 0.38474217, 0.32955302, 0.34030327,
        0.46179525],
       [0.22458056, 0.36315326, 0.66975804, 0.18199019, 0.85454977,
        0.09441998]])

### <a name='5'></a> Exercise 15

Set the random seed to 20. Then build a two-dimensional array with the shape _(10, 4)_ pseudo-random values generated from the standard normal distribution $ N (0, 1) $.

__Expected result:__
```
array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.79201679, -0.84236793, -1.27950266,  0.24571517],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843],
       [-0.1686461 , -3.18970279,  1.12013226,  1.33277821],
       [-0.24333877, -0.13003071, -0.10901737,  1.55618644],
       [ 0.12877835, -2.06694872, -0.88549315, -1.10457948],
       [ 0.93286635,  2.059838  , -0.93493796, -1.61299022],
       [ 0.52706972, -1.55110074,  0.32961334, -1.13652654]])
```
__Tip:__ Use the function _np.random.randn()_.


In [16]:
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html
np.random.randn(10,4)


array([[-0.8874175 ,  0.40260576, -0.38495661, -0.50866755],
       [ 1.10615412, -0.47543028, -1.626025  ,  1.69402503],
       [-1.0294561 ,  1.05458297, -1.47459301,  0.87624628],
       [-0.86840406, -1.1913032 , -0.10869765,  0.74950472],
       [ 0.29864571, -0.20888145,  0.62075444, -0.54023779],
       [ 0.38500743, -2.2554046 , -1.263571  , -1.60668944],
       [-0.17750559,  0.64546947,  0.55831474, -0.87651613],
       [-0.94813304, -0.73279363, -0.59901953, -0.20616233],
       [-1.2462888 ,  1.24659957, -1.52589192, -0.47733737],
       [ 0.43733195,  0.00637735, -0.18779906, -0.40582706]])

### <a name='6'></a> Exercise 16
Set the random seed to 30. Then build a two-dimensional array with the shape _(10, 4)_ pseudo-random values generated from the normal distribution $ N (100, 5) $.
$\mu=100$   
$\sigma^{2}=5$

__Expected result:__
```
array([[ 97.17349231, 103.41650023,  97.82942436, 101.05220329],
       [ 99.7748353 , 100.67930221,  96.14063068, 103.544381  ],
       [100.30029631,  97.52499594, 103.52901961, 100.24037271],
       [ 98.29153712,  98.2666258 , 103.09437633, 101.70027274],
       [ 99.36127721, 101.20382627,  95.34026547, 102.09694365],
       [ 99.98708001,  98.95468525,  99.05410904, 102.38025432],
       [ 93.50787269, 103.61547679, 103.18753701,  98.51356237],
       [102.20256689,  96.19764407,  97.54000366,  97.05813038],
       [101.81233513,  97.66380453,  98.45883627,  98.09317768],
       [102.48979932,  95.70413391,  98.43161651, 101.89861815]])
```
__Tip:__ Use the function _np.random.rand()_.


In [21]:
# enter solution here
np.random.rand(10,4)*100

array([[57.31034208,  8.69759332, 46.92119774, 68.38361954],
       [40.93422196, 44.61485416, 14.32838735,  9.44918401],
       [47.72872444, 48.22615705, 35.47355434, 52.97630418],
       [67.13129342,  7.11186893, 70.37872191, 73.96312486],
       [35.38135911, 96.43849944, 46.59919832, 47.13170135],
       [ 8.88978874, 19.74994807, 37.06044884, 16.82526367],
       [88.35139063, 81.91627998, 45.59488888, 14.94973348],
       [86.77221801, 16.56236481, 48.28211639, 43.51772108],
       [38.12494647, 42.06129858,  1.16581944, 99.90979534],
       [42.90672206,  1.76795631, 57.99832281, 42.34090168]])

### <a name='7'></a> Exercise 17
Iterating by array numpy $ A $ element by element (element-wise) print each element of the array to the console.

```
A = np.array([[1, 4, 3],
              [5, 2, 6]])
```

__Tip:__ Use the _np.nditer()_ function.


In [24]:
# https://numpy.org/doc/stable/reference/generated/numpy.nditer.html

A = np.array([[1, 4, 3],
              [5, 2, 6]])
# np.nditer(A)
for item in np.nditer(A):
  print(item)


1
4
3
5
2
6


### <a name='8'></a> Exercise 18
Create a one-dimensional numpy array (vector) consisting of 11 equally spaced points from the interval $ [0, 1]. $

__Expected result:__
```
array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
```
__Tip:__ Use the _np.linspace()_ function.



In [31]:
# https://numpy.org/doc/stable/reference/generated/numpy.linspace.html
np.linspace(0,1,dtype=float,num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### <a name='9'></a> Exercise 19

Set the random seed to 42. Generate a one-dimensional array (vector) containing the possible result from the Big Lotto game.

__Expected result:__
```
array([39, 29, 15, 43,  8, 21])
```

__Tip:__ The result of the game is a 6-element vector of values from 1 to 49 inclusive.



In [41]:
# enter solution here
# https://stackoverflow.com/questions/22071987/generate-random-array-of-floats-between-a-range
# np.random.uniform(1,50,size = (5))
# np.random.random_integers(1,50,size = (5))
np.random.randint(1,50,size = (5))

# https://numpy.org/doc/stable/reference/random/generated/numpy.random.uniform.html

array([35, 20, 23, 16, 19])

### <a name='10'></a> Exercise 20
Build the two-dimensional _6x6_ size array below:

```
array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])
```
__Tip:__ Use the _np.diag()_ function.



In [46]:
# https://numpy.org/doc/stable/reference/generated/numpy.diag.html
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])